<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class AttendancesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 実際に存在するユーザーIDを取得
        $userIds = User::pluck('id')->toArray();

        if (empty($userIds)) {
            throw new \Exception('No users found. Please create users before running AttendancesTableSeeder.');
        }

        DB::table('attendances')->insert([
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-01',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-02',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-03',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-04',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-07',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-08',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-09',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-10',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-11',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-14',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-15',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-16',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-17',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-18',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-21',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-22',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-23',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-24',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-25',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-28',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-29',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-30',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-07-31',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-01',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-01',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-04',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-04',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-05',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-05',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-06',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-06',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-07',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-07',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-08',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-08',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-18',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-18',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-19',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-19',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-20',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-20',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-21',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-21',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-22',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-22',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-25',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-25',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-26',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-26',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-27',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-27',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-28',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-28',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-08-29',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-08-29',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-09-01',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-09-01',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-09-02',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-09-02',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-09-03',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-09-03',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-09-04',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-09-04',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-09-05',
                'start_time' => '9:00',
                'end_time' => '18:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-09-05',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[1],
                'date' => '2025-09-08',
                'start_time' => '9:00',
                'end_time' => '12:00',
                'note' => '',
            ],
            [
                'user_id' => $userIds[2],
                'date' => '2025-09-08',
                'start_time' => '08:30',
                'end_time' => '15:00',
                'note' => '',
            ],
        ]);
    }
}
